# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: AJ Halling
title: Recent Graduate - B.S. Information Systems
email: aj.halling7@gmail.com
website: https://ajhalling.com

# Social links
twitter_username: ajhalling
github_username:  ajhalling
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: ajhalling
linkedin_username: aj-halling
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  My name is AJ and I've recently graduated with my degree in Information Systems. I have worked jobs in tech for over 6 years beginning in device sales, moving to repair, and most recently systems administration. I have also have skills in <mark>Python</mark>, <mark>HTML/CSS</mark>, and <mark>AWS</mark>.
  /
  I'm currently looking for a job in the Salt Lake City area. I'm open to discussing potential job opportunities, so please reach out! I am searching for a position as a Systems Analyst or Engineer, DevOps Engineer, or Data Analyst. 

# Education Section
# educaton_title: Education

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience



# More Section
# more_title: A Little More About Me
# more_content: | # this will include new lines to allow paragraphs
#   Alongside my interests in networks and software engineering some of my other interests and hobbies are:
#    - Rock climbing
#    - Gaming
#    - Knitting
#    - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
